// flow-typed signature: e11abab90e653cc70c8df18176c74095
// flow-typed version: <<STUB>>/rollup-plugin-node-builtins_v^2.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-builtins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-node-builtins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-node-builtins/browser-test/dist/bundle' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/browser-test/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/browser-test/main' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/build-constants' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/dist/constants' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/rollup.config' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/assert' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/console' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/domain' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/empty' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/events' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/http-lib/capability' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/http-lib/request' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/http-lib/response' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/http' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/inherits' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/os' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/path' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/punycode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/qs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/buffer-list' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/duplex' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/passthrough' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/readable' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/transform' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/writable' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/setimmediate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/stream' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/string-decoder' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/timers' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/tty' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/url' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/util' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/vm' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/adler32' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/binding' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/crc32' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/deflate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inffast' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inflate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inftrees' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/messages' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/trees' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/utils' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/zstream' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/es6/zlib' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-builtins/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-node-builtins/browser-test/dist/bundle.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/browser-test/dist/bundle'>;
}
declare module 'rollup-plugin-node-builtins/browser-test/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/browser-test/index'>;
}
declare module 'rollup-plugin-node-builtins/browser-test/main.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/browser-test/main'>;
}
declare module 'rollup-plugin-node-builtins/build-constants.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/build-constants'>;
}
declare module 'rollup-plugin-node-builtins/dist/constants.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/dist/constants'>;
}
declare module 'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.cjs'>;
}
declare module 'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.es6.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/dist/rollup-plugin-node-builtins.es6'>;
}
declare module 'rollup-plugin-node-builtins/rollup.config.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/rollup.config'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/assert.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/assert'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/console.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/console'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/domain.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/domain'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/empty.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/empty'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/events.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/events'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/http-lib/capability.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/http-lib/capability'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/http-lib/request.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/http-lib/request'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/http-lib/response.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/http-lib/response'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/http-lib/to-arraybuffer'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/http.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/http'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/inherits.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/inherits'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/os.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/os'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/path.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/path'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/punycode.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/punycode'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/qs.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/qs'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/buffer-list.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/buffer-list'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/duplex'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/passthrough.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/passthrough'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/readable.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/readable'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/transform.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/transform'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/readable-stream/writable.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/readable-stream/writable'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/setimmediate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/setimmediate'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/stream.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/stream'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/string-decoder.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/string-decoder'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/timers.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/timers'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/tty.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/tty'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/url.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/url'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/util.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/util'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/vm.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/vm'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/adler32.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/adler32'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/binding.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/binding'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/crc32.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/crc32'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/deflate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/deflate'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inffast.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/inffast'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inflate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/inflate'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/inftrees.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/inftrees'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/messages.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/messages'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/trees.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/trees'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/utils'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib-lib/zstream.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib-lib/zstream'>;
}
declare module 'rollup-plugin-node-builtins/src/es6/zlib.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/es6/zlib'>;
}
declare module 'rollup-plugin-node-builtins/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-builtins/src/index'>;
}
