// flow-typed signature: 3f906d2df83cfe2d33fcbf7065376afe
// flow-typed version: <<STUB>>/@sharkcore/eslint-config_v^1.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sharkcore/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sharkcore/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@sharkcore/eslint-config/index' {
  declare module.exports: $Exports<'@sharkcore/eslint-config'>;
}
declare module '@sharkcore/eslint-config/index.js' {
  declare module.exports: $Exports<'@sharkcore/eslint-config'>;
}
