// flow-typed signature: 15b7ac914fca8feeaa22cb9550600d3c
// flow-typed version: <<STUB>>/yargs-parser_v^7.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yargs-parser/lib/tokenize-arg-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yargs-parser/index' {
  declare module.exports: $Exports<'yargs-parser'>;
}
declare module 'yargs-parser/index.js' {
  declare module.exports: $Exports<'yargs-parser'>;
}
declare module 'yargs-parser/lib/tokenize-arg-string.js' {
  declare module.exports: $Exports<'yargs-parser/lib/tokenize-arg-string'>;
}
